FROM node:22-alpine

WORKDIR /app
ENV NODE_ENV=production
ENV TZ=Asia/Ho_Chi_Minh

RUN apk add --no-cache tzdata

COPY package.json package-lock.json ./
RUN npm ci --include=dev

COPY prisma ./prisma
COPY src ./src
COPY tsconfig.json ./

RUN npx prisma generate

CMD ["npx", "prisma", "migrate", "deploy"]
