global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    environment: k8s-lab
    project: qltrungtam

alerting:
  alertmanagers:
    - static_configs:
        - targets: [alertmanager:9093]

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [prometheus:9090]

  - job_name: node
    static_configs:
      - targets: [172.16.0.2:9100]
        labels: {node: cp1, role: control-plane}
      - targets: [172.16.0.1:9100]
        labels: {node: cp2, role: control-plane}
      - targets: [172.16.0.3:9100]
        labels: {node: cp3, role: control-plane}
      - targets: [172.16.0.5:9100]
        labels: {node: worker1, role: worker}
      - targets: [172.16.0.4:9100]
        labels: {node: worker2, role: worker}
      - targets: [172.16.0.6:9100]
        labels: {node: monitor, role: monitoring}

  - job_name: postgres
    static_configs:
      - targets: [172.16.0.21:9187]
        labels:
          role: application-database

  - job_name: kube-state-metrics
    static_configs:
      - targets: [172.16.0.22:8080]

  - job_name: blackbox
    static_configs:
      - targets: [blackbox-exporter:9115]

  - job_name: app-probe
    metrics_path: /probe
    params:
      module: [http_app_health]
    static_configs:
      - targets: [http://172.16.0.20/api/health]
        labels:
          service: qltrungtam
          environment: k8s-lab
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
